[2024-10-29T18:39:57.777+0000] {processor.py:186} INFO - Started process (PID=2550) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:39:57.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:39:57.781+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:39:57.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:39:57.800+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:39:57.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:39:57.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:39:57.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.057 seconds
[2024-10-29T18:40:28.147+0000] {processor.py:186} INFO - Started process (PID=2558) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:28.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:40:28.151+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:28.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:28.169+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:28.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:40:28.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:28.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.054 seconds
[2024-10-29T18:40:58.561+0000] {processor.py:186} INFO - Started process (PID=2566) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:58.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:40:58.566+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:58.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:58.588+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:58.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:40:58.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:58.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:40:59.627+0000] {processor.py:186} INFO - Started process (PID=2567) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:59.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:40:59.630+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:59.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:59.652+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:40:59.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:40:59.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:40:59.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.063 seconds
[2024-10-29T18:41:30.083+0000] {processor.py:186} INFO - Started process (PID=2575) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:30.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:41:30.086+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:41:30.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:30.104+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:41:30.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:41:30.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:30.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.058 seconds
[2024-10-29T18:41:40.319+0000] {processor.py:186} INFO - Started process (PID=2583) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:40.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:41:40.322+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:41:40.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:40.337+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:41:40.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 36
    @task(task_id="writeKafka")
    ^
IndentationError: expected an indented block after function definition on line 34
[2024-10-29T18:41:40.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:41:40.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.054 seconds
[2024-10-29T18:42:00.584+0000] {processor.py:186} INFO - Started process (PID=2584) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:00.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:42:00.587+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:00.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:00.616+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:00.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:42:00.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:00.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.065 seconds
[2024-10-29T18:42:06.766+0000] {processor.py:186} INFO - Started process (PID=2592) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:06.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:42:06.770+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:06.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:06.805+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:06.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:42:06.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:06.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:42:37.216+0000] {processor.py:186} INFO - Started process (PID=2600) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:37.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:42:37.219+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:37.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:37.242+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:37.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:42:37.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:37.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.063 seconds
[2024-10-29T18:42:57.512+0000] {processor.py:186} INFO - Started process (PID=2601) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:57.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:42:57.515+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:57.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:57.551+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:42:57.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:42:57.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:42:57.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.072 seconds
[2024-10-29T18:43:27.931+0000] {processor.py:186} INFO - Started process (PID=2609) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:27.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:43:27.934+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:43:27.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:27.954+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:43:27.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:43:27.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:27.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.056 seconds
[2024-10-29T18:43:58.379+0000] {processor.py:186} INFO - Started process (PID=2617) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:58.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:43:58.382+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:43:58.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:58.400+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:43:58.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:43:58.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:43:58.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.053 seconds
[2024-10-29T18:44:02.536+0000] {processor.py:186} INFO - Started process (PID=2619) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:02.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:02.539+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:02.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:02.561+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:02.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 75
    extra=json.dumps({"socket.timeout.ms": 10, "bootstrap.servers": "broker:29092"}),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: extra
[2024-10-29T18:44:02.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:02.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T18:44:05.597+0000] {processor.py:186} INFO - Started process (PID=2626) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:05.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:05.600+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:05.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:05.620+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:05.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 75
    extra=json.dumps({"socket.timeout.ms": 10, "bootstrap.servers": "broker:9092"}),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: extra
[2024-10-29T18:44:05.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:05.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.055 seconds
[2024-10-29T18:44:13.785+0000] {processor.py:186} INFO - Started process (PID=2627) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:13.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:13.788+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:13.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:13.810+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:13.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 75
    extra=json.dumps({"socket.timeout.ms": 10, "bootstrap.servers": "broker:9092"}),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: extra
[2024-10-29T18:44:13.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:13.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.058 seconds
[2024-10-29T18:44:16.925+0000] {processor.py:186} INFO - Started process (PID=2628) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:16.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:16.928+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:16.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:16.962+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:16.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:16.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:16.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:44:20.024+0000] {processor.py:186} INFO - Started process (PID=2629) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:20.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:20.027+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:20.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:20.060+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:20.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:20.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:20.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.070 seconds
[2024-10-29T18:44:22.117+0000] {processor.py:186} INFO - Started process (PID=2630) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:22.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:22.122+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:22.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:22.162+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:22.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:22.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:22.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.098 seconds
[2024-10-29T18:44:27.223+0000] {processor.py:186} INFO - Started process (PID=2631) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:27.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:27.226+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:27.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:27.283+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:27.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:27.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:27.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.102 seconds
[2024-10-29T18:44:30.346+0000] {processor.py:186} INFO - Started process (PID=2632) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:30.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:30.349+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:30.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:30.379+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:30.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:30.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:30.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.062 seconds
[2024-10-29T18:44:32.432+0000] {processor.py:186} INFO - Started process (PID=2633) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:32.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:32.435+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:32.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:32.471+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:32.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:32.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:32.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.076 seconds
[2024-10-29T18:44:34.588+0000] {processor.py:186} INFO - Started process (PID=2642) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:34.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:34.591+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:34.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:34.625+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:34.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:34.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:34.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:44:37.679+0000] {processor.py:186} INFO - Started process (PID=2643) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:37.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:37.682+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:37.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:37.714+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:37.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:37.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:37.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T18:44:42.829+0000] {processor.py:186} INFO - Started process (PID=2644) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:42.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:42.833+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:42.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:42.882+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:42.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:42.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:42.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.113 seconds
[2024-10-29T18:44:44.898+0000] {processor.py:186} INFO - Started process (PID=2645) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:44.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:44.901+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:44.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:44.936+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:44.931+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:44.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:44.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.081 seconds
[2024-10-29T18:44:48.061+0000] {processor.py:186} INFO - Started process (PID=2646) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:48.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:48.065+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:48.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:48.135+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:48.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:48.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:48.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.130 seconds
[2024-10-29T18:44:52.148+0000] {processor.py:186} INFO - Started process (PID=2647) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:52.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:52.151+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:52.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:52.189+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:52.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:52.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:52.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.081 seconds
[2024-10-29T18:44:54.224+0000] {processor.py:186} INFO - Started process (PID=2648) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:54.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:54.228+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:54.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:54.262+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:54.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:54.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:54.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.070 seconds
[2024-10-29T18:44:56.333+0000] {processor.py:186} INFO - Started process (PID=2649) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:56.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:44:56.336+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:56.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:56.377+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:44:56.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:44:56.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:44:56.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.078 seconds
[2024-10-29T18:45:26.749+0000] {processor.py:186} INFO - Started process (PID=2657) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:26.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:45:26.752+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:45:26.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:26.774+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:45:26.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:45:26.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:26.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T18:45:57.175+0000] {processor.py:186} INFO - Started process (PID=2665) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:57.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:45:57.178+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:45:57.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:57.194+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:45:57.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:45:57.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:45:57.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.049 seconds
[2024-10-29T18:46:27.604+0000] {processor.py:186} INFO - Started process (PID=2673) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:27.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:46:27.608+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:46:27.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:27.631+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:46:27.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:46:27.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:27.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T18:46:58.032+0000] {processor.py:186} INFO - Started process (PID=2681) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:58.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:46:58.036+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:46:58.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:58.060+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:46:58.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:46:58.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:46:58.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T18:47:28.471+0000] {processor.py:186} INFO - Started process (PID=2689) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:28.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:47:28.474+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:47:28.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:28.494+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:47:28.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:47:28.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:28.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.056 seconds
[2024-10-29T18:47:56.857+0000] {processor.py:186} INFO - Started process (PID=2697) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:56.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:47:56.860+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:47:56.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:56.894+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:47:56.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:47:56.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:47:56.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.072 seconds
[2024-10-29T18:48:00.967+0000] {processor.py:186} INFO - Started process (PID=2698) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:00.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:00.970+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:00.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:01.004+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:00.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:01.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:01.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T18:48:23.328+0000] {processor.py:186} INFO - Started process (PID=2706) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:23.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:23.331+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:23.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:23.366+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:23.361+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:23.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:23.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:48:32.473+0000] {processor.py:186} INFO - Started process (PID=2707) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:32.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:32.476+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:32.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:32.511+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:32.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:32.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:32.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.072 seconds
[2024-10-29T18:48:36.578+0000] {processor.py:186} INFO - Started process (PID=2714) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:36.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:36.581+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:36.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:36.613+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:36.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:36.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:36.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.077 seconds
[2024-10-29T18:48:37.735+0000] {processor.py:186} INFO - Started process (PID=2716) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:37.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:37.738+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:37.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:37.771+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:37.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:37.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:37.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T18:48:41.830+0000] {processor.py:186} INFO - Started process (PID=2717) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:41.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:41.834+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:41.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:41.866+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:41.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:41.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:41.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.067 seconds
[2024-10-29T18:48:53.059+0000] {processor.py:186} INFO - Started process (PID=2718) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:53.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:48:53.065+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:53.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:53.128+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:48:53.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:48:53.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:48:53.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.118 seconds
[2024-10-29T18:49:00.168+0000] {processor.py:186} INFO - Started process (PID=2719) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:00.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:00.171+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:00.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:00.188+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:00.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 166
    start_date=datetime(2024-, 1, 1),
                             ^
SyntaxError: invalid syntax
[2024-10-29T18:49:00.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:00.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.053 seconds
[2024-10-29T18:49:02.226+0000] {processor.py:186} INFO - Started process (PID=2720) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:02.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:02.229+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:02.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:02.262+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:02.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:02.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:02.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.070 seconds
[2024-10-29T18:49:05.403+0000] {processor.py:186} INFO - Started process (PID=2727) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:05.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:05.406+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:05.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:05.442+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:05.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:05.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:05.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.074 seconds
[2024-10-29T18:49:09.583+0000] {processor.py:186} INFO - Started process (PID=2729) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:09.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:09.586+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:09.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:09.619+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:09.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:09.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:09.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.067 seconds
[2024-10-29T18:49:10.641+0000] {processor.py:186} INFO - Started process (PID=2730) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:10.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:10.644+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:10.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:10.677+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:10.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:10.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:10.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.070 seconds
[2024-10-29T18:49:27.902+0000] {processor.py:186} INFO - Started process (PID=2731) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:27.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:27.904+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:27.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:27.939+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:27.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:27.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:27.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.074 seconds
[2024-10-29T18:49:56.346+0000] {processor.py:186} INFO - Started process (PID=2739) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:56.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:56.349+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:56.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:56.370+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:56.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 184
    th a keyword argument."
                          ^
SyntaxError: unterminated string literal (detected at line 184)
[2024-10-29T18:49:56.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:56.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.057 seconds
[2024-10-29T18:49:58.479+0000] {processor.py:186} INFO - Started process (PID=2740) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:58.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:49:58.481+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:58.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:58.514+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:49:58.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:49:58.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:49:58.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.068 seconds
[2024-10-29T18:50:00.555+0000] {processor.py:186} INFO - Started process (PID=2741) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:00.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:00.559+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:00.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:00.593+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:00.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:00.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:00.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.077 seconds
[2024-10-29T18:50:06.690+0000] {processor.py:186} INFO - Started process (PID=2748) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:06.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:06.693+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:06.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:06.723+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:06.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:06.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:06.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.066 seconds
[2024-10-29T18:50:08.778+0000] {processor.py:186} INFO - Started process (PID=2749) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:08.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:08.780+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:08.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:08.811+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:08.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:08.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:08.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.073 seconds
[2024-10-29T18:50:28.152+0000] {processor.py:186} INFO - Started process (PID=2751) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:28.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:28.155+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:28.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:28.186+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:28.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:28.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:28.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.076 seconds
[2024-10-29T18:50:30.213+0000] {processor.py:186} INFO - Started process (PID=2752) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:30.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:30.216+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:30.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:30.238+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:30.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 213
    t0 >> t1, t3] >> t2
                ^
SyntaxError: unmatched ']'
[2024-10-29T18:50:30.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:30.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.061 seconds
[2024-10-29T18:50:33.334+0000] {processor.py:186} INFO - Started process (PID=2753) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:33.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:33.338+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:33.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:33.375+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:33.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:33.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:33.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.079 seconds
[2024-10-29T18:50:37.417+0000] {processor.py:186} INFO - Started process (PID=2760) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:37.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:37.421+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:37.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:37.454+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:37.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:37.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:37.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T18:50:45.620+0000] {processor.py:186} INFO - Started process (PID=2762) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:45.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:45.623+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:45.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:45.656+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:45.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:45.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:45.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.085 seconds
[2024-10-29T18:50:51.771+0000] {processor.py:186} INFO - Started process (PID=2763) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:51.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:50:51.775+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:51.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:51.809+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:50:51.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:50:51.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:50:51.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T18:51:22.235+0000] {processor.py:186} INFO - Started process (PID=2771) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:22.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:51:22.239+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:51:22.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:22.259+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:51:22.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:51:22.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:22.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.058 seconds
[2024-10-29T18:51:52.642+0000] {processor.py:186} INFO - Started process (PID=2779) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:52.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:51:52.645+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:51:52.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:52.668+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:51:52.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:51:52.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:51:52.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T18:52:23.162+0000] {processor.py:186} INFO - Started process (PID=2787) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:23.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:52:23.178+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:52:23.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:23.415+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:52:23.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:52:23.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:23.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.329 seconds
[2024-10-29T18:52:53.657+0000] {processor.py:186} INFO - Started process (PID=2795) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:53.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:52:53.664+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:52:53.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:53.688+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:52:53.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 10, in <module>
    from airflow.providers.apache.kafka.operators.produce import ProduceToTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-10-29T18:52:53.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:52:53.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.069 seconds
[2024-10-29T18:58:32.183+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:58:32.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:58:32.192+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:58:32.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:58:32.218+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:58:32.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T18:58:32.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:58:32.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.104 seconds
[2024-10-29T18:59:02.622+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:02.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:59:02.626+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:59:02.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:02.650+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:59:02.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T18:59:02.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:02.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.064 seconds
[2024-10-29T18:59:33.026+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:33.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T18:59:33.030+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:59:33.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:33.052+0000] {logging_mixin.py:190} INFO - [2024-10-29T18:59:33.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T18:59:33.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T18:59:33.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.065 seconds
[2024-10-29T19:00:03.547+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:03.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:00:03.552+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:00:03.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:03.572+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:00:03.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:00:03.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:03.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.071 seconds
[2024-10-29T19:00:33.736+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:33.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:00:33.739+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:00:33.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:33.761+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:00:33.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:00:33.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:00:33.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.062 seconds
[2024-10-29T19:01:04.171+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:04.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:01:04.174+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:01:04.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:04.193+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:01:04.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:01:04.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:04.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.059 seconds
[2024-10-29T19:01:34.591+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:34.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:01:34.595+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:01:34.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:34.618+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:01:34.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:01:34.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:01:34.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.066 seconds
[2024-10-29T19:02:05.147+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:05.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:02:05.151+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:02:05.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:05.174+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:02:05.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:02:05.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:05.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.063 seconds
[2024-10-29T19:02:35.636+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:35.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:02:35.642+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:02:35.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:35.666+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:02:35.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:02:35.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:02:35.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.075 seconds
[2024-10-29T19:03:06.066+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:06.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:03:06.069+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:03:06.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:06.092+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:03:06.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:03:06.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:06.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.060 seconds
[2024-10-29T19:03:36.543+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:36.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/write_kafka.py for tasks to queue
[2024-10-29T19:03:36.546+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:03:36.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:36.569+0000] {logging_mixin.py:190} INFO - [2024-10-29T19:03:36.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/write_kafka.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/write_kafka.py", line 25, in <module>
    @task(task_id="getCME")
     ^^^^
NameError: name 'task' is not defined
[2024-10-29T19:03:36.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/write_kafka.py
[2024-10-29T19:03:36.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/write_kafka.py took 0.060 seconds
